//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BallonDorEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BallonDorEntities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;year&quot;: &quot;1956&quot;,
        ///    &quot;winnerFirstName&quot;: &quot;Stanley&quot;,
        ///    &quot;winnerLastName&quot;: &quot;Matthews&quot;,
        ///    &quot;winnerPosition&quot;: &quot;attacker&quot;,
        ///    &quot;winnerFullName&quot;: &quot;Stanley Matthews&quot;
        ///  },
        ///  {
        ///    &quot;year&quot;: &quot;1957&quot;,
        ///    &quot;winnerFirstName&quot;: &quot;Alfredo&quot;,
        ///    &quot;winnerLastName&quot;: &quot;Di Stefano&quot;,
        ///    &quot;winnerPosition&quot;: &quot;attacker&quot;,
        ///    &quot;winnerFullName&quot;: &quot;Alfredo Di Stefano&quot;
        ///  },
        ///  {
        ///    &quot;year&quot;: &quot;1958&quot;,
        ///    &quot;winnerFirstName&quot;: &quot;Raymond&quot;,
        ///    &quot;winnerLastName&quot;: &quot;Kopa&quot;,
        ///    &quot;winnerPosition&quot;: &quot;attacker&quot;,
        ///    &quot;winnerFullName&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string staticDB {
            get {
                return ResourceManager.GetString("staticDB", resourceCulture);
            }
        }
    }
}
